// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'KEY',
    appId: '1:600090546549:web:f16f1ee63036041309833c',
    messagingSenderId: '600090546549',
    projectId: 'rob-game',
    authDomain: 'rob-game.firebaseapp.com',
    storageBucket: 'rob-game.appspot.com',
    measurementId: 'G-HW8GC1FVS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'KEY',
    appId: '1:600090546549:android:a9aa875e3bb827ce09833c',
    messagingSenderId: '600090546549',
    projectId: 'rob-game',
    storageBucket: 'rob-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'KEY',
    appId: '1:600090546549:ios:211bf8e39ceb937809833c',
    messagingSenderId: '600090546549',
    projectId: 'rob-game',
    storageBucket: 'rob-game.appspot.com',
    iosBundleId: 'com.example.robsGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'KEY',
    appId: '1:600090546549:ios:211bf8e39ceb937809833c',
    messagingSenderId: '600090546549',
    projectId: 'rob-game',
    storageBucket: 'rob-game.appspot.com',
    iosBundleId: 'com.example.robsGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'KEY',
    appId: '1:600090546549:web:591d3657c1e0ceea09833c',
    messagingSenderId: '600090546549',
    projectId: 'rob-game',
    authDomain: 'rob-game.firebaseapp.com',
    storageBucket: 'rob-game.appspot.com',
    measurementId: 'G-R0TWPL6E3J',
  );
}
